### ISSUE TITLE
R package for caterva (Proposal)

### ISSUE THREAD

**Issue by kokitsuyuzaki** [Blosc/python-caterva#45]
Thanks for the great tool.
Have you thought about a caterva package for the R language (r-caterva)?
R/Bioconductor packages for large scale genome analysis use HDF5 format at the moment, but if Caterva can make the process faster, it would be quite an innovation.

**Comment by FrancescAlted** [comment]
Yes, we thought about that, but we are a small team, and we decided to support just the Python wrapper, at least initially. But we encourage others to produce different wrappers for other languages indeed.

**Comment by kokitsuyuzaki** [comment]
Thanks. I hope this project will be a success!
